# 1. Julia en 10 minutes

Point abordés : 
1. Vos amis "documentation" et "complétion"
1. Noms de variables
1. Nombres
1. Booléens
1. Chaînes de caractères
1. Ranges
1. Arrays (tableaux)
1. Tuples
1. Dictionnaires
1. Boucles `for`et `while`
1. Instructions conditionnelles
1. Fonctions
1. Exemple 1: sécante
1. Exemple 2: manipulation de matrices


----
## 1. Aide, documentation et complétion

**Vous ne savez plus ce que la fonction sinus fait ni même comment elle s'écrit ?**  Vous avez alors deux amis: 
- `?` documentations
- `<TAB>` complétion 

Tappez `?si<TAB>` et les différentes possibilités apparaîtront.

In [9]:
?si      # positionné le curseur après "?si" et faite <tab> pour avoir toutes les commandes commençant par "si"

search: sub2ind sin size sinh sind sinc sign sinpi sizeof signif signed Signed

Couldn't find si
Perhaps you meant sin, pi, sign, sinc, sind, sinh, size, asin, skip, sec or std


No documentation found.

Binding `si` does not exist.


----
## 2. Noms de variables



In [ ]:
x = 1                   # affecte l'objet entier à la variable x 
                        #     et affiche le résultats sou le REPL ou sous notebook
x = 1 ;                 # affecte l'objet entier à la variable x 
                        #     et N'AFFICHE PAS le résultat sous le REPL ou sous notebook

En Julia les noms de variables sont constitués de caractères UTF-8, cela peut être intéressant:

In [10]:

une_variable = "test"   # conseil: noms en minuscules avec des underscores
itération = 1           # notez l'accent qui est autorisé
σ = 1                   # tapper \sigma   suivi de <tab>    (complétion: tappez \s: suivi de <tab>)
🎱 = 1.                 # tapper \:8ball: suivi de <tab>    (complétion: tappez \: suivi de <tab>)
σ == 🎱                 # σ et 🎱 sont égaux.... (notez le caractère "8 ball" en italique...) 

true

----
## 3. Nombres

Parmi les nombres possibles:

In [97]:
8            # nombre entier,     de type Int64 (codé en 64 bits)
8.12         # nombre réel,       de type Float64
8 + 2im      # nombre complexe,   de type Complex{Int64}   (construit avec des Int64)
8. + 2im     # nombre complexe,   de type Complex{Float64} (construit avec des Float64)
8//9         # nombre rationnel,  de type Rational{Int64}  (construit avec des Int64)
println("un nombre rationel : ",4//3, # (on peut couper une ligne de commande en deux)
    " de type ",typeof(3//4))         # println : affiche ses arguments suivis d'un "\n" (new line)
                                      # typeof : affiche le type de ses arguments

un nombre rationel : 4//3 de type Rational{Int64}


La partie imaginaire est notée `im`, on peut utiliser la notation `8+2im` ou `8+2*im`. On a bien:

In [11]:
im^2

-1 + 0im

On dispose des opérations classiques:

In [12]:
3 + 1      
4 - 3      
10 * 2
2^3
sqrt(3)
20/3                    # division 
20\3                    # inverse de 20/3, i.e. 3/20            20/3 est 1/(20\3)
div(20,3)               # division tronquée à un entier
20%3                    # reste de la division précédente       20 = 3 * div(20,3) + 20%3 

2

In [168]:
x = 0.5
1 + 2x # notez qu'il n'est pas nécessaire d'écrire 1+2*x
       # en revanche 1+x*2 ne peut pas s'écrire 1+x2 

2.0

----
## 4. Booléens

In [18]:
true                    # vrai
false                   # faux
!true                   # faux
1 == 1                  # vrai
1 != 1                  # faux
1 == 1.                 # vrai
1 != 2                  # vrai, 1 est différent de 2
3 > 7                   # est faux
2 >= 2                  # est vrai
5 < 7 < 18.
true & false            # est faux,  "et" logique
true | false            # est vrai,  "ou" logique
true == 1               # ça il sait le faire, il admet que true peut se comprendre comme 1 
true == 1. 

true

In [19]:
a = 1
b = 1.
a == b                  # a et b sont égaux comme nombres

true

----
## 5. Chaînes de caractères



Les chaînes de caractères et les caractères ont des syntaxes différentes:

In [20]:
x = "a"                 # ceci est le chaîne de caractères ne contenat que la lettre 'a'
y = 'a'                 # ceci est le caractère 'a' ('aa' n'a pas exemple pas de sens)
x == y

false

### Construction des chaînes 

In [112]:
chaîne = readline()     # lit la ligne suivante (depuis le std input)

STDIN> dss


"dss"

In [123]:
chaîne  = "5/2 vaut $(5/2)"                         # => "5/2 vaut 2.5"
x, y = 1.2, 2.3
chaîne  = "le résultats est $(x+y)"                 # => "le résultats est 3.5"
chaîne  = @printf "%d est inférieur à %f" 4.5 5.8   # => "5 est inférieur à 5.800000"

5 est inférieur à 5.800000

In [135]:
chaîne1 = """Une autre possibilité de créer\n des chaînes de caractères\n θ 🍺"""
chaîne2 = """Une autre possibilité de créer
des chaînes de caractères
θ 🍺"""
chaîne1 == chaîne2

true

In [136]:
println(chaîne1)        # interprète les caractères spéciaux

Une autre possibilité de créer
des chaînes de caractères
θ 🍺


### Opérations sur les caractères

In [21]:
'a' + 1                 # => 'b'
'a' * 'a'               # => "aa" (chaine de caractères)
'b' - 'a'               # => 1 équivalent à Int('b')-Int('a')
'z' - 'a'               # => 25
'a' < 'b'               # => true
'A' < 'a'               # => true

true

### Opération sur les chaînes

In [25]:
"bière" < "theta"       # => true
"123" * "456"           # => "123456" (concaténation)

"123456"

In [26]:
println(  search("Les petits pois sont rouges", 'i')                ,"\n",
          search("Les petits pois sont rouges", 'i', 8)             ,"\n",
          contains("Les petits pois sont rouges", "pois")           ,"\n",
          length("Les petits pois sont rouges")                     ,"\n",
          replace("Les petits pois sont rouges","rouges","verts")   ,"\n",
          "Les petits pois sont rouges"[3:8]                        ,"\n",
          uppercase("Les petits pois sont rouges")                      )

8
8
true
27
Les petits pois sont verts
s peti
LES PETITS POIS SONT ROUGES


On peut parcourir les caractères d'une chaîne:

In [27]:
for c in "un 🌵 vert"
    print(c)
end

un 🌵 vert

On peut aussi construire des sous-chaines de caractères:

In [30]:
"abcdefg"[2]                  # => 'b'     (c'est un Char)
"abcdefg"[2:4]                # => "bcd"   (c'est un String)
"abcdefg"[2:end]              # => "bcdefg"
"abcdefg"[end:-1:1]           # => "gfedcba" équivalent à reverse("abcdefg")
split("You know my name")     # => ["You", "know", "my", "name"]
split("You know my name","n") # => ["You k", "ow my ", "ame"]

3-element Array{SubString{String},1}:
 "You k" 
 "ow my "
 "ame"   

----
## 6. Ranges

On a déjà vu des expressions comme `"abcdefg"[2:4]` où la chaine de caractères `"abcdefg"` est vue comme une suite de caractères et  `"abcdefg"[2:4]`  et la sous-chaine comprenant les caractères 2 à 4, ici `[2:4]` représente la suite des indices concernés, en fait cet objet est de type `Range` qu'il faut comprendre un minimum.

Le type `range`, qui sera utile par exemple dans les boucle `for`, permet aussi de créer des arrays. On peut le construire par pas selone la syntaxe:
```
   début:[pas:]fin
```
ou par longueur selon la syntaxe:
```
  range(début,[pas,]longueur)
```
on peut créer des objets équivalents grace à
```
  linspace(début,fin,longueur)
```

In [53]:
mes_ranges = (
    1:5,                # de 1 à 5 par pas de 1 
    range(1,6),         # 6 termes à partir de 1
    1:2:6,              #  par pas de 2
    linspace(0,10,4),   # de 0 à 10 en 4 termes
    1.5:2.1:8,          # aussi valable pour les non-entiers
    8:-1:0)             # pas négatif
for i in mes_ranges                                     # la boucle for est très simple
    println(rpad(i,28),"  ",length(i),"  ",collect(i))  # rpad: affiche son arg à gauche d'une colonne de 12
end                                                     # caractères; length: nb de termes

1:5                           5  [1, 2, 3, 4, 5]
1:6                           6  [1, 2, 3, 4, 5, 6]
1:2:5                         3  [1, 3, 5]
0.0:3.3333333333333335:10.0   4  [0.0, 3.33333, 6.66667, 10.0]
1.5:2.1:7.8                   4  [1.5, 3.6, 5.7, 7.8]
8:-1:0                        9  [8, 7, 6, 5, 4, 3, 2, 1, 0]


In [45]:
x = 0:e:7 
step(x)                 # pas du range ici c'est e
length(x)               # nombre de termes du range
round.(x)               # on peut "broadcaster" une fonction sur le range avec le "."
sin.(x)                 #  idem
y = collect(x)          # converti les ranges en arrays (cf. infra)
pop!(y)                 # y est modifié en place

0.0:2.718281828459045:5.43656365691809

----
## 7. Arrays

Les arrays (tableaux) permettent aussi de représenter des vecteurs et des matrice (voir Exemple 2 infra). Ils sont **mutables**.


Un array est une **collection ordonnée de termes**. On peut créer des arrays vides ou non, contenant des types différents ou des types spécifiques. En Julia, les tableaux sont utilisés pour les listes, les vecteurs, les tableaux et les matrices.

### Construction d'arrays

In [138]:
a = [1:5;]              # => [1, 2, 3, 4, 5] identique à collect(1:5)  
b = [1:5]               # => un array avec un élément de type range 1:5
println(a)
println(b)
typeof(a),typeof(b)

[1, 2, 3, 4, 5]
UnitRange{Int64}[1:5]


(Array{Int64,1}, Array{UnitRange{Int64},1})

In [133]:
x = [1, 2, 3]           # array de Int64                Array{Int64,1}
x = [1; 2; 3]           # même objet
x = [1., 2, 3]          # array de Float64              Array{Float64,1}
x = ["pois", "rouges"]  # array de String               Array{String,1}
x = [sin, cos, tan]     # array de fontions Function    Array{Function,1}
x = ["pois", cos, 1.]   # array de n'importe quoi       Array{Any,1}

3-element Array{Any,1}:
  "pois"
  cos   
 1.0    

##### Création d'arrays en imposant les types:

In [139]:
x    = Array{Any}(3)    # un tableau de 3 termes de tout type
x[1] = 1 
x[2] = 'a'
Float64[1, 2, 3, 4]     # un tableau de réels contenant 1.0, 2.0 etc
y    = Array{Int}(3)
y[1] = 2.2              # ERREUR
z    = Float16[]        # idem à Array{Float16}()

LoadError: InexactError()

##### Création d'arrays préremplis

In [101]:
x = (rand(2),           # un array 2x1 de nombres aléatoires U[0,1]
    ones(2,3),          # un array 2x3 de 1
    zeros(2,3),         # idem mais avec des 0
    eye(2))             # matrice identité 2x2
for i in x
    println(typeof(i), "  ",i)
end

Array{Float64,1}  [0.60959, 0.365728]
Array{Float64,2}  [1.0 1.0 1.0; 1.0 1.0 1.0]
Array{Float64,2}  [0.0 0.0 0.0; 0.0 0.0 0.0]
Array{Float64,2}  [1.0 0.0; 0.0 1.0]


##### Création d'arrays sous forme Vecteurs et matrices:

In [140]:
Vector(5)
Matrix(5, 5)

5×5 Array{Any,2}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

### Slicing

Le **slicing** à l'aide de `Range`:

In [65]:
x = ['a', 'b', 'c', 'd', 'e', 'f']
x[1]         # => 'a'
x[end]       # => 'f'
x[1:2:end]   # => ['a', 'c', 'e']

3-element Array{Char,1}:
 'a'
 'c'
 'e'

### Opérations sur les array

deux fonctions de tri qui modifient ou non le tableau en place

certaines opérations **modifient en place** les tableaux, le nom de ces opérations se termine par "!":

In [116]:
x = [2, 1, 3]
sort(x)   # => [1,2,3] et x est [2,1,3]
sort!(x)  # => [1,2,3] et x est [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [134]:
x = [1, 2, 3]
pop!(x)             # rend le dernier terme de x     et modifie x qui est [1, 2]
pop!(x)             # rend le dernier terme de x     et modifie x qui est [1]
push!(x,2)          # rajoute un terme à la fin de x et modifie x qui est [1, 2]
push!(x,3)          # rajoute un terme à la fin de x et modifie x qui est [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

##### Broadcasting

*Broadcaster une fonction sur un array* signifie appliquer une même fonction `fonction` à tous les éléments d'un array `tableau`:
```
   fonction.(tableau)
```

In [296]:
x = π*(0:0.5:2)  # de 0 à 2π par pas de π/2
x = cos.(x)      # dispatch de cosinus sur x
round.(x,1)      # dispatch de round sur x

5-element Array{Float64,1}:
  1.0
  0.0
 -1.0
 -0.0
  1.0

Définir des **fonctions sur les arrays** à l'aide du broadcast:

In [324]:
f(x) = sin.(x.^2+1)    # 1) f s'applique à des array
r1 = f(1:5)            #    on applique f à un range (un array)
g(x) =  sin(x^2+1)     # 2) g s'applique à des nombres
r2 = g.(1:5)           #    on broadcaste g sur un array
h(x) = sin.(x.^2+1)    # 3) ça marche aussi 
r3 = h.(1:5)           #    même si c'est plus curieux
r1 == r2 == r3         # => true  (tous des Array{Float64,1})

true

### Les arrays sont **mutables**

In [68]:
x    = [1, 2, 3]
y    = x
y[1] = 0     # modifie aussi x
x    

3-element Array{Int64,1}:
 0
 2
 3

# 8. Tuples

Un `tuple` est une séquence ordonnée d'éléments, comme un array. Un tuple est représenté par des **parenthèses** et des virgules, plutôt que par les crochets utilisés par les tableaux. Les tuples servent pour les petites collections de longueur fixe. Ils sont utilisés partout dans Julia, par exemple comme des listes d'arguments et pour renvoyer plusieurs valeurs de fonctions.

Contrairement aux arrays, les **tuples sont immuables**, mais ils partagent de nombreuses fonctions:

In [24]:
a = (1,2,3)
a[1]
a[1] = 2

LoadError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [25]:
a = [1,2,3]
try
    a[end+1] # BoundsError: attempt to access 3-element Array{Int64,1} at index [4]
catch e
    println("non")
end

non


In [66]:
x = [1, 2 ,3]
y = x
y[1] = 0
x

3-element Array{Int64,1}:
 0
 2
 3

 # 9. Dictionnaires et ensembles

## Expressions conditionnelles

## Fonctions

In [ ]:
f(x) = cos.(0.01x.^2)+x.*(3-x)+1    # on veut l'utiliser sur des array
ff = x -> cos.(0.01x.^2)+x.*(3-x)+1 # style anonymous

In [26]:
a = [1:5]
b = [1:5;]
b

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

## Exemple 1: méthode de la dichotomie

La [méthode de la dichotomie](https://fr.wikipedia.org/wiki/Méthode_de_dichotomie) est un [algorithme de recherche d'un zéro d'une fonction](https://fr.wikipedia.org/wiki/Algorithme_de_recherche_d%27un_zéro_d%27une_fonction).

In [27]:
function dichotomie( f::Function, a, b; itémax=500, tolérance=1e-8)  # le premier argument sera une fonction
    
    fa, fb = f(a), f(b)
    fa*fb > 0 ? error("f(a) et f(b) doivent être de signe différent") : nothing

    for i in 1:itémax
        m  = (a+b)/2
        fm = f(m)
        
        abs(fm) > tolérance ? nothing : return(m,fm)
        
        if fa*fm > 0
            a, fa = m, fm
        else
            b, fb = m, fm
        end
    end
   
    error("Pas de convergence en $itémax itérations")

end

dichotomie (generic function with 1 method)

In [28]:
f(x) = cos.(0.01x.^2)+x.*(3-x)+1    # on veut l'utiliser sur des array
ff = x -> cos.(0.01x.^2)+x.*(3-x)+1 # style anonymous

(::#4) (generic function with 1 method)

In [ ]:
println(dichotomie(f,0,10))
println(dichotomie(ff,0,10)) # même chose

Un peu de graphique à du package `Plots`:

In [37]:
# Pkg.add("Plots") # si ce n'est déjà fait
using Plots

In [38]:
a, b = 0, 5
solution, fsolution = dichotomie(f,a,b)
x = a:0.01:b
plot(x,f(x),label="fonction f")                  # tracé de f
scatter!((solution, fsolution),label="solution") # rajoute un point

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 0 
 
 
 1 
 
 
 2 
 
 
 3 
 
 
 4 
 
 
 5 
 
 
 -7.5 
 
 
 -5.0 
 
 
 -2.5 
 
 
 0.0 
 
 
 2.5 
 
<polyline clip-path="url(#clip3202)" style="stroke:#009af9; stroke-width:1; stroke-opacity:1; fill:none" points="
 54.808,85.0318 55.8284,84.1956 56.8488,83.365 57.8692,82.54 58.8896,81.7206 59.9101,80.9068 60.9305,80.0986 61.9509,79.2959 62.9713,78.4989 63.9917,77.7074 
 65.0121,76.9216 66.0325,76.1413 67.0529,75.3667 68.0733,74.5976 69.0937,73.8341 70.1141,73.0762 71.1345,72.3239 72.1549,71.5772 73.1753,70.8361 74.1957,70.1006 
 75.2161,69.3707 76.2365,68.6463 77.2569,67.9276 78.2773,67.2145 79.2977,66.5069 80.3181,65.805 81.3385,65.1086 82.3589,64.4178 83.3793,63.7326 84.3997,63.0531 
 85.4201,62.3791 86.4405,61.7107 87.4609,61.0479 88.4813,60.3907 89.5017,59.7391 90.5221,59.093 91.5425,58.4526 92.5629,57.8178 93.5833,57.1885 94.6037,56.5649 
 95.6241,55.9468 96.6445,55.3344 97.6649,54.7275 98.6853,54.1262 99.7057,53.5306 100.726,52.9405 101.747,52.356 102.767,51.7771 103.787,51.2038 104.808,50.6361 
 105.828,50.0739 106.849,49.5174 107.869,48.9665 108.889,48.4212 109.91,47.8814 110.93,47.3473 111.951,46.8187 112.971,46.2957 113.991,45.7784 115.012,45.2666 
 116.032,44.7604 117.053,44.2598 118.073,43.7648 119.093,43.2754 120.114,42.7916 121.134,42.3134 122.155,41.8408 123.175,41.3738 124.195,40.9124 125.216,40.4565 
 126.236,40.0063 127.257,39.5616 128.277,39.1226 129.297,38.6891 130.318,38.2613 131.338,37.839 132.359,37.4223 133.379,37.0112 134.399,36.6058 135.42,36.2059 
 136.44,35.8116 137.461,35.4229 138.481,35.0398 139.501,34.6622 140.522,34.2903 141.542,33.924 142.563,33.5633 143.583,33.2081 144.603,32.8586 145.624,32.5146 
 146.644,32.1763 147.665,31.8435 148.685,31.5164 149.705,31.1948 150.726,30.8788 151.746,30.5684 152.767,30.2637 153.787,29.9645 154.807,29.6709 155.828,29.3829 
 156.848,29.1005 157.869,28.8236 158.889,28.5524 159.909,28.2868 160.93,28.0268 161.95,27.7724 162.971,27.5235 163.991,27.2803 165.011,27.0426 166.032,26.8106 
 167.052,26.5841 168.073,26.3633 169.093,26.148 170.113,25.9383 171.134,25.7343 172.154,25.5358 173.175,25.3429 174.195,25.1556 175.215,24.9739 176.236,24.7978 
 177.256,24.6273 178.277,24.4624 179.297,24.3031 180.317,24.1494 181.338,24.0013 182.358,23.8588 183.379,23.7219 184.399,23.5905 185.419,23.4648 186.44,23.3447 
 187.46,23.2301 188.481,23.1212 189.501,23.0178 190.521,22.9201 191.542,22.8279 192.562,22.7414 193.583,22.6604 194.603,22.585 195.623,22.5153 196.644,22.4511 
 197.664,22.3925 198.685,22.3395 199.705,22.2921 200.725,22.2503 201.746,22.2142 202.766,22.1836 203.787,22.1586 204.807,22.1392 205.828,22.1254 206.848,22.1172 
 207.868,22.1145 208.889,22.1175 209.909,22.1261 210.93,22.1403 211.95,22.1601 212.97,22.1855 213.991,22.2164 215.011,22.253 216.032,22.2952 217.052,22.3429 
 218.072,22.3963 219.093,22.4553 220.113,22.5198 221.134,22.59 222.154,22.6657 223.174,22.7471 224.195,22.834 225.215,22.9266 226.236,23.0247 227.256,23.1285 
 228.276,23.2378 229.297,23.3527 230.317,23.4733 231.338,23.5994 232.358,23.7311 233.378,23.8685 234.399,24.0114 235.419,24.1599 236.44,24.3141 237.46,24.4738 
 238.48,24.6391 239.501,24.81 240.521,24.9866 241.542,25.1687 242.562,25.3564 243.582,25.5497 244.603,25.7486 245.623,25.9532 246.644,26.1633 247.664,26.379 
 248.684,26.6003 249.705,26.8272 250.725,27.0597 251.746,27.2978 252.766,27.5416 253.786,27.7909 254.807,28.0458 255.827,28.3063 256.848,28.5724 257.868,28.8441 
 258.888,29.1214 259.909,29.4043 260.929,29.6929 261.95,29.987 262.97,30.2867 263.99,30.592 265.011,30.9029 266.031,31.2194 267.052,31.5415 268.072,31.8692 
 269.092,32.2026 270.113,32.5415 271.133,32.886 272.154,33.2361 273.174,33.5918 274.194,33.9531 275.215,34.3201 276.235,34.6926 277.256,35.0707 278.276,35.4544 
 279.296,35.8437 280.317,36.2387 281.337,36.6392 282.358,37.0453 283.378,37.4571 284.398,37.8744 285.419,38.2973 286.439,38.7259 287.46,

## Exemple 2: manipuler les matrices

In [86]:
Vector(5)

5-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef
 #undef

In [87]:
Matrix(5, 5)

5×5 Array{Any,2}:
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef

In [88]:
rand(4,3)

4×3 Array{Float64,2}:
 0.624419  0.112935  0.689244
 0.153553  0.159717  0.958318
 0.104109  0.757374  0.130699
 0.595133  0.158374  0.420211

In [89]:
collect(3.5:9.5)

7-element Array{Float64,1}:
 3.5
 4.5
 5.5
 6.5
 7.5
 8.5
 9.5

In [92]:
x = [1,2,3,4,5]   # vecteur colonne
y = [1 2 3 4 5]   # vecteur ligne
x                 # essayer avec y

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [147]:
ones(3,4)

3×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [149]:
zeros(1,3)

1×3 Array{Float64,2}:
 0.0  0.0  0.0

In [150]:
rand(2,2)

2×2 Array{Float64,2}:
 0.519928  0.333002
 0.229126  0.661973

In [153]:
eye(2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [152]:
?eyes

search: hex2bytes readbytes! eye KeyError speye eltype keytype supertype

Couldn't find eyes
Perhaps you meant eye, keys, eigs, eps, ones, Sys, speye, e, edit, eig or eof


No documentation found.

Binding `eyes` does not exist.


In [154]:
x = Vector(4)

4-element Array{Any,1}:
 #undef
 #undef
 #undef
 #undef

In [162]:
x = rand(2,1)
typeof(x)
rand(2,2)*x

2×1 Array{Float64,2}:
 0.832802
 0.921686